name: Docker Build and Deploy

on:
  push:
    branches:
      - main
env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCEKR_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    TAG: ${{ github.sha }}
    TAG_LATEST: latest

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCEKR_ACCESS_TOKEN }}

      - name: Build Docker image with static tag
        run: make build

      - name: Push Docker image to Docker Hub with static tag
        run: make push

      - name: Build Docker image with latest tag
        run: TAG=${{ env.TAG_LATEST }} make build

      - name: Push Docker image to Docker Hub with latest tag
        run: TAG=${{ env.TAG_LATEST }} make push
